### ISSUE TITLE
Odoo 10 Enterprise issue

### ISSUE THREAD

**Issue by promotobillet** [idazco/odoo_auth0#4]
I receive these errors when trying to install on Odoo 10 Enterprise.

> Odoo Session Expired
Your Odoo session expired. Please refresh the current web 
> page.

> Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 377, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 270, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 138, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 367, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/opt/odoo/custom/addons/auth0/__init__.py", line 2, in <module>
    from . import controllers
  File "/opt/odoo/custom/addons/auth0/controllers/__init__.py", line 2, in <module>
    from . import main
  File "/opt/odoo/custom/addons/auth0/controllers/main.py", line 11, in <module>
    import jwt
ImportError: No module named jwt
> 

Also the app has to be removed and server restarted, or no login is possible.

**Comment by sylnsr** [comment]
For now, just add the missing dependency: `pip install pyjwt`
Thanks for pointing this out. I will add it to the documentation.
Let me know if that worked for you.

**Comment by sylnsr** [comment]
Documentation updated

**Comment by promotobillet** [comment]
pyjwt installed, odoo restarted, updated apps list, and tried to install auth0 module produced the following error:

> Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 411, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/module/module.py", line 485, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 377, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 270, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 138, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 367, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/opt/odoo/custom/addons/auth0/__init__.py", line 2, in <module>
    from . import controllers
  File "/opt/odoo/custom/addons/auth0/controllers/__init__.py", line 2, in <module>
    from . import main
  File "/opt/odoo/custom/addons/auth0/controllers/main.py", line 11, in <module>
    import jwt
ImportError: No module named jwt

>

**Comment by sylnsr** [comment]
The package we use for `jwt` is the one in the documentation, and the source is here: https://github.com/jpadilla/pyjwt .. it can be a bit confusing because the project is called `pyjwt` but in code package is called `jwt` .. so correct installation is `pip install pyjwt`
If your Odoo deployment's Python environment is not seeing the package that pip installed then you have a problem with your Python environment or some other installation problem.  For example, you might have installed the package in a virtual environment, but Odoo is using the system environment.

**Comment by sylnsr** [comment]
Are you running Odoo in the host's Python env; in a Python virtual
environment; or in some OS virtualized environment such as LXC or Docker ?

**Comment by sylnsr** [comment]
Closing issue because this was resolved onsite for the OP (no code issue found)
